# WEB PROPERTIES
server:
  port: 880
  ssl:
    key-store: 'classpath:config/keystore.pfx'
    key-store-password: 214576205430625
    key-store-type: PKCS12

# SPRING
spring:
  # DATASOURCE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost/pet?useUnicode=true&characterEncoding=UTF-8'
    username: root
    password: 123456
